# Generated by Django 5.2.7 on 2025-11-07 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_book_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='cd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('departments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='office.department')),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
