# Generated by Django 5.2.7 on 2025-11-07 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_cd_delete_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cd',
            new_name='Employee',
        ),
    ]
